### ISSUE TITLE
Add more .env files for the switcher

### ISSUE THREAD

**Issue by avkonst** [EcksDy/vscode-env-switcher#15]
Thanks for the useful tool. 
Is it possible to improve it so it could discover available env files not by file extension but also by a a file prefix. For example all the following would be candidates for env switcher:

```
.env.local
.env.dev
.local.env
.dev.env
```

**Comment by EcksDy** [comment]
Hey @avkonst, thank you for taking interest in the extension!

There's a refactor I've started a while ago and postponed for a long time, I'd like to roll it out before adding new features. 
I'll take a look at how I can add your feature in the next couple of weeks.

**Comment by EcksDy** [comment]
It's been a while, thank you for the wait :)
New version is up, you can run `Extensions: Check for Extension Updates` to force an update.

Please go over the `README` as there are new configs added to find the target files and the presets.
