### ISSUE TITLE
Allow us to specify the environment file name

### ISSUE THREAD

**Issue by metamoof** [EcksDy/vscode-env-switcher#19]
I'm currently developing azure functions, and instead of a `.env` file, the environment variables are stored in a `local.settings.json` file.

Would it be possible to add a preference that would allow us to configure per workspace what the environment file is called? Also, some sort of regex or glob pattern that would allow me to specify that in this workspace, you should look for alternatives that are `local.settings.prod.json` or `local.settings.testing.json`? This could also be handy for #15

**Comment by EcksDy** [comment]
Hey @metamoof, thank you for posting an issue!

To be honest, I wasn't considering other configuration files when I was first developing this extension. This does seem like a useful feature that can be added relatively easily.

I will probably add workspace settings to allow for any glob pattern and default it to search for `.env`.

**Comment by EcksDy** [comment]
It's been a while, thank you for the wait :)
New version is up, you can run `Extensions: Check for Extension Updates` to force an update.

Please go over the `README` as there are new configs added to find the target files and the presets.

**Comment by metamoof** [comment]
Hiya,

Back from holiday and back to the grind.

I'm on Windows, using vs code insiders and version 0.4.1 of the extension.

I have the following settings in my workspace;

```json
{
    "envSwitcher.glob.presets": "**/local.settings.*.json"
    "envSwitcher.glob.target": "**/local.settings.json"
}
``` 

I have the following files in the root of my workspace:
- `local.settings copy.json`
- `local.settings prod.json`
- `local.settings.dev-testdb.json`
- `local.settings.dev.json`
- `local.settings.json`
- `local.settings.testing.json`

I receive the following error when attempting to select preset: `Unable to resolve filesystemprovider with relative file path 'c:\Users\garadford\Dev\UMA\tge-ax-bc-functiona\local.settings.testing.json'`

What am I doing wrong?

---- 

VS Code version:
Version: 1.82.0-insider (user setup)
Commit: 1606401f5b761397488f53b75130809fba073194
Date: 2023-08-07T05:34:17.393Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
