### ISSUE TITLE
env switcher updates wrong .env file

### ISSUE THREAD

**Issue by avkonst** [EcksDy/vscode-env-switcher#20]
I have multiple .env files in my repo, one is in the root of the repo, others in subfolders. I would like env switcher to update .env in the root, but it picks some random in a subfolder. Would it be possible to fix it? BTW, your tool is very useful!

**Comment by EcksDy** [comment]
Hey @avkonst,
Thank you for your patience! 
I didn't have the time to maintain the extension properly, but now I'm working on it again :)

As for the issue, can you provide me with a tree diagram of the file names and relevant directories in your project so I can reproduce it? Something along the lines of:
```
project-root/
├─ presets/
│  ├─ .env
│  ├─ staging.env
├─ .env
```
You can use this tool: https://ascii-tree-generator.com/

Also what's your `envSwitcher.presetsGlob` configuration in the settings?

**Comment by avkonst** [comment]
envSwitcher.presetsGlob is '*'

**Comment by avkonst** [comment]
file tree is .env in the root of a repo and lots of sub-folders with deeply nested .env files inside, some of these .env files are even committed to git.
I want the extension to update the .env in the root of a repo, but it updates the one which it finds in a deeply nested subfolder. Sometimes it does not find the exact same again and again, but picks only random one in a subfolder.

**Comment by franelj** [comment]
Hi,

I do have the same problem, .ENV Switcher systematically updates a .env file in subfolders instead of updating the one at the project root.

Here is my file tree : 
```
my_app/
├─ node_modules/
│  ├─ @fastify/
│  │  ├─ env/
│  │  │  ├─ test/
│  │  │  │  ├─ .env
├─ .env
├─ .local.env
```
`envSwitcher.presetsGlob` is set to *.

Thank you :)

**Comment by d-reader-josip** [comment]
Same thing. It copies the content from selected .env files to an .env file. But not the .env from my root, instead it copies the content from an .env file from a random node_module
![image](https://user-images.githubusercontent.com/125173470/236424300-2f622f85-38a3-40c4-a413-7798e698ef2a.png)

**Comment by EcksDy** [comment]
This should be resolved in the new version next week.
Thank you for the info, will add to test scenarios as I go.

**Comment by EcksDy** [comment]
New version is up, you can run `Extensions: Check for Extension Updates` to force an update.

Please go over the `README` as there are new configs added to find the target files and the presets.
