### ISSUE TITLE
Alert before altering .env

### ISSUE THREAD

**Issue by acarter24** [EcksDy/vscode-env-switcher#34]
As discussed in https://github.com/EcksDy/vscode-env-switcher/issues/27#issuecomment-1658557381

- Enable an Alert box when switching env with content something like this: 'You are about to permanently overwrite the contents of {full_env_file_path}. This cannot be reversed/undone. Please read the docs for more info. OK/cancel'
- Alert should be on by default to avoid first time users being surprised by behaviour.
- Allow the alert to be turned off via the extension config once you are happy with .envswitcher workflow.

The app name kind of suggests you are 'switching' between files, which you are :) but if you already have content in a top level .env file then you might not expect this to be overwritten the first time you use it.

**Comment by EcksDy** [comment]
`v0.4.3` is up, you can run `Extensions: Check for Extension Updates` to force an update.

I've simplified the message string as I dislike "debug data" in a working interface. 
I've added a `overwriteAlert` config. It will be disabled for all workspaces if you press `Don't show again` on the alert.

**Comment by acarter24** [comment]
Thanks, tested and works well. 

One this I noticed is if you 'close' the notification using the 'x' in the top right, that has the same effect as clicking 'OK'. There's probably not much you can do about that though.
