### ISSUE TITLE
Comand '.ENV Switcher: Select preset' resulted in an error

### ISSUE THREAD

**Issue by d-reader-josip** [EcksDy/vscode-env-switcher#35]
This is the error I get after running the command:
![image](https://github.com/EcksDy/vscode-env-switcher/assets/125173470/23adc6a7-706c-4977-8760-89078a15537f)

These are my .env files which I have in the root:
![image](https://github.com/EcksDy/vscode-env-switcher/assets/125173470/f085ca39-efe7-47a9-afa7-de1803d4fdf7)

This is my configuration:
```
  "envSwitcher.glob.target": "**/*.env",
  "envSwitcher.glob.targetExclude": "**/node_modules/**,**/config/env/**,**/.env.example"
```

I have some encrypted .env files in the /config/env folder, hence why I'm ignoring that whole folder.
I'm on windows, not using WSL. I've reinstalled the extension and reloaded VSC

Any ideas? Is this an issue on my end or?

**Comment by EcksDy** [comment]
Thank you for posting an issue 🙏 

This seems like a platform specific issue with windows :(
If you can make a reproduction repo with your file structure and some dummy content in the files, then I will certainly take a look at it on a windows machine over the weekend and try to hotfix if it's small enough. 

I'm currently working on a testing suite that I intend to run in github actions on all available platforms to catch such issues. If you can't make the repro-repo, then we'll wait for the automated tests to resurface this issue.

**Comment by EcksDy** [comment]
`v0.4.2` is up, you can run `Extensions: Check for Extension Updates` to force an update.

Leaving this open for a while in case there are still issues.

**Comment by EcksDy** [comment]
Seems like it's resolved 🎉
