### ISSUE TITLE
Consider adding a license file

### ISSUE THREAD

**Issue by natefabian18** [EcksDy/vscode-env-switcher#43]
For completeness sake we should consider setting up a license file. I always reference https://choosealicense.com.  

Bonus this will remove one of the warnings on [actions](https://github.com/EcksDy/vscode-env-switcher/actions/runs/5833389413). Im not familiar enough with github actions to suggest something for the other warning.

**Comment by EcksDy** [comment]
Heya, 
glad to see you stick around!

License was added as part of #44 , the warning was bugging me as well :)
